apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-rest-audit
  name: kube-rest-audit
  namespace: kube-rest-audit
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-rest-audit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-rest-audit
    spec:
      containers:
      - image: docker.io/richardoc/kube-rest-audit:$COMMIT
        imagePullPolicy: IfNotPresent
        name: kube-rest-audit
        ports:
        - containerPort: 9090
          protocol: TCP
          name: https
        volumeMounts:
        - name: certs
          mountPath: "/etc/tls"
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          secretName: kube-rest-audit
